# After changing this file, check it on:
# http://lint.travis-ci.org/
language: node_js
# Is `sudo` required? If not, jobs are run on container-based infrastructure.
sudo: required
dist: trusty
node_js:
  - "stable"
  - "6"
  - "5"
  - "4"
matrix:
  fast_finish: true

os:
  - linux
  - osx

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-$EMULATOR_API_VER
     # The SDK version used to compile your project
    - android-23
     # Additional components
    - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-$EMULATOR_API_VER
    - addon-google_apis-google-23

addons:
#  firefox: "38.0"
  apt:
    sources:
      # needed to install g++ that is used by npms's native modules
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - zip
      - libgtk2.0-0
      - g++
      - google-chrome-stable

cache:
  directories:
    - node_modules

before_install:
  - ./scripts/ci/before.sh

install:
  - ./scripts/ci/install.sh

script:
  - ./scripts/ci/test.sh

after_success:
  - ./scripts/ci/after.sh

notifications:
  email:
    on_success: change
    on_failure: change
