language: node_js
sudo: required
dist: trusty
node_js:
  - "stable"
  - "5"
  - "6"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - g++
      - google-chrome-stable

cache:
  directories:
    - node_modules

install:
  - ./scripts/ci/install.sh

script:
  - ./scripts/ci/test.sh
