# After changing this file, check it on:
# http://lint.travis-ci.org/
language: node_js
# Is `sudo` required? If not, jobs are run on container-based infrastructure.
sudo: required
dist: trusty
node_js:
  - "stable"
  - "5"
  - "6"

addons:
#  firefox: "38.0"
  apt:
    sources:
      # needed to install g++ that is used by npms's native modules
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - g++
      - google-chrome-stable

cache:
  directories:
    - node_modules

before_install:
  - ./tools/ci/before.sh

install:
  - ./tools/ci/install.sh

script:
  - ./tools/ci/test.sh

after_success:
  - ./tools/ci/after.sh

notifications:
  email:
    on_success: change
    on_failure: change